apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: socket-swap-role
rules:
- apiGroups: ["batch", ""]
  resources: ["jobs", "cronjobs", "pods"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
