apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base

images:
  - name: socket-swap-image
    newName: ghcr.io/zeroows/socket-swap
    newTag: dev

# Optional: Add dev-specific patches
patches:
  - target:
      kind: Deployment
      name: socket-swap-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "600"  # Longer TTL for dev
